CREATE TABLE `users` (
	`id` TINYINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
	`fullname` VARCHAR(50) NOT NULL COLLATE 'utf8_czech_ci',
	`createdAt` DATETIME NOT NULL,
	`updatedAt` DATETIME NULL DEFAULT NULL,
	`birthDate` DATE NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_czech_ci'
ENGINE=InnoDB;
